### ISSUE TITLE
Archery experience not showing correctly

### ISSUE THREAD

**Issue by swim709** [Stephirio/MCMMOAdditions#5]
Default config will not show you the current XP of the Archery skill.

Change the
     lore:
      - '&2You have &6%mcmmo_xp_**rarchery**% &bXP&2.'

to

lore:
      - '&2You have &6%mcmmo_xp_**archery**% &bXP&2.'

and the problem is fixed  :)

**Comment by Stephirio** [comment]
Thank you so much for reporting this!
